version: '3.3'
services:
  todo-app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=qwerty
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: timdb
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./input_data.sql:/docker-entrypoint-initdb.d/input_data.sql