version: '3.3'
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: timdb
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./input_data.sql:/docker-entrypoint-initdb.d/input_data.sql
  timdb:
    build: ./
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ${TAG}:/local