apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: tim
  POSTGRES_PASSWORD: "123"
  POSTGRES_DB: timdb

  DB_HOST: fullstack-postgres
  DB_DRIVER: postgres
  API_SECRET: "98hbun98h"
  DB_USER: tim
  DB_PASSWORD: "123"
  DB_NAME: timdb
  DB_PORT: "5432"