apiVersion: v1
kind: ServiceAccount
metadata:
  name: podkicker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podkicker
rules:
  - apiGroups: ["apps"]
    verbs: ["patch","get","list"]
    resources:
      - "deployments"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podkicker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podkicker
subjects:
  - kind: ServiceAccount
    name: podkicker
